version: '3'
services:
        web:
                build: .
                ports:
                        - "8080:8080"
                volumes:
                        - ./src:/usr/local/apache2/htdocs
